### ISSUE TITLE
No reviews pushed back to gerrit after upgrade of sonar to 5.1

### ISSUE THREAD

**Issue by tisoft** [tech-advantage/sonar-gerrit-plugin#11]
After upgrading sonar to version 5.1 no issues are sent bacj to gerrit anymore. It seems to me that the GerritDecorator and GerritPostJob classes are not initalized and run anymore.

This is the debug output of a run with sonar 5.1. I only included lines containing gerrit. If you need the full log, i can send it to you.

[DEBUG] [15:33:54.954] [GERRIT PLUGIN] Instanciating GerritConfiguration
[DEBUG] [15:33:54.955] [GERRIT PLUGIN] Instanciating GerritConnector
[DEBUG] [15:33:55.220] [GERRIT PLUGIN] Instanciating GerritFacade
[DEBUG] [15:33:55.221] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:33:55.228] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:33:55.229] Initializer GerritInitializer
[DEBUG] [15:33:55.229] [GERRIT PLUGIN] Built URI : /gerrit2/a/changes/XXX~master~Icea820260e2d011abe27fc20ea01dba395f3d74e/revisions/989415b44c8ed5afdd367dc0962f4d1a2116fac5
[INFO] [15:33:55.230] [GERRIT PLUGIN] Listing files from /gerrit2/a/changes/XXX~master~Icea820260e2d011abe27fc20ea01dba395f3d74e/revisions/989415b44c8ed5afdd367dc0962f4d1a2116fac5/files/
[INFO] [15:33:55.474] [GERRIT PLUGIN] Request 1: GET to /gerrit2/a/changes/XXX~master~Icea820260e2d011abe27fc20ea01dba395f3d74e/revisions/989415b44c8ed5afdd367dc0962f4d1a2116fac5/files/
[DEBUG] [15:33:55.561] Executing request GET /gerrit2/a/changes/XXX~master~Icea820260e2d011abe27fc20ea01dba395f3d74e/revisions/989415b44c8ed5afdd367dc0962f4d1a2116fac5/files/ HTTP/1.1
[DEBUG] [15:33:55.568] http-outgoing-0 >> GET /gerrit2/a/changes/XXX~master~Icea820260e2d011abe27fc20ea01dba395f3d74e/revisions/989415b44c8ed5afdd367dc0962f4d1a2116fac5/files/ HTTP/1.1
[DEBUG] [15:33:55.573] http-outgoing-0 >> "GET /gerrit2/a/changes/XXX~master~Icea820260e2d011abe27fc20ea01dba395f3d74e/revisions/989415b44c8ed5afdd367dc0962f4d1a2116fac5/files/ HTTP/1.1[\r][\n]"
[DEBUG] [15:33:55.578] http-outgoing-0 << "WWW-Authenticate: Digest realm="Gerrit Code Review", domain="http://XXX/gerrit2/", qop="auth", nonce="XXX==$"[\r][\n]"
[DEBUG] [15:33:55.589] http-outgoing-0 << WWW-Authenticate: Digest realm="Gerrit Code Review", domain="http://XXX/gerrit2/", qop="auth", nonce="XXX==$"
[DEBUG] [15:33:55.604] Executing request GET /gerrit2/a/changes/XXX~master~Icea820260e2d011abe27fc20ea01dba395f3d74e/revisions/989415b44c8ed5afdd367dc0962f4d1a2116fac5/files/ HTTP/1.1
[DEBUG] [15:33:55.613] http-outgoing-0 >> GET /gerrit2/a/changes/XXX~master~Icea820260e2d011abe27fc20ea01dba395f3d74e/revisions/989415b44c8ed5afdd367dc0962f4d1a2116fac5/files/ HTTP/1.1
[DEBUG] [15:33:55.614] http-outgoing-0 >> Authorization: Digest username="sonarqube", realm="Gerrit Code Review", nonce="XXX==$", uri="/gerrit2/a/changes/XXX~master~Icea820260e2d011abe27fc20ea01dba395f3d74e/revisions/989415b44c8ed5afdd367dc0962f4d1a2116fac5/files/", response="db167e5465beb70b1b4d7a76fc4df646", qop=auth, nc=00000001, cnonce="XXX", algorithm=MD5
[DEBUG] [15:33:55.614] http-outgoing-0 >> "GET /gerrit2/a/changes/XXX~master~Icea820260e2d011abe27fc20ea01dba395f3d74e/revisions/989415b44c8ed5afdd367dc0962f4d1a2116fac5/files/ HTTP/1.1[\r][\n]"
[DEBUG] [15:33:55.615] http-outgoing-0 >> "Authorization: Digest username="sonarqube", realm="Gerrit Code Review", nonce="XXX==$", uri="/gerrit2/a/changes/XXX~master~Icea820260e2d011abe27fc20ea01dba395f3d74e/revisions/989415b44c8ed5afdd367dc0962f4d1a2116fac5/files/", response="db167e5465beb70b1b4d7a76fc4df646", qop=auth, nc=00000001, cnonce="XXX", algorithm=MD5[\r][\n]"
[INFO] [15:33:55.713] Initializer GerritInitializer (done) | time=484ms
[DEBUG] [15:33:55.966] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:33:55.967] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:33:55.967] Initializer GerritInitializer
[DEBUG] [15:33:55.967] [GERRIT PLUGIN] File list already filled. Not calling Gerrit.
[INFO] [15:33:55.967] Initializer GerritInitializer (done) | time=0ms
[DEBUG] [15:34:00.584] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:34:00.585] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:34:00.585] Initializer GerritInitializer
[DEBUG] [15:34:00.585] [GERRIT PLUGIN] File list already filled. Not calling Gerrit.
[INFO] [15:34:00.585] Initializer GerritInitializer (done) | time=0ms
[DEBUG] [15:34:20.537] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:34:20.539] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:34:20.539] Initializer GerritInitializer
[DEBUG] [15:34:20.539] [GERRIT PLUGIN] File list already filled. Not calling Gerrit.
[INFO] [15:34:20.539] Initializer GerritInitializer (done) | time=0ms
[DEBUG] [15:34:34.910] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:34:34.911] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:34:34.911] Initializer GerritInitializer
[DEBUG] [15:34:34.911] [GERRIT PLUGIN] File list already filled. Not calling Gerrit.
[INFO] [15:34:34.911] Initializer GerritInitializer (done) | time=0ms
[DEBUG] [15:35:20.939] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:35:20.940] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:35:20.940] Initializer GerritInitializer
[DEBUG] [15:35:20.940] [GERRIT PLUGIN] File list already filled. Not calling Gerrit.
[INFO] [15:35:20.940] Initializer GerritInitializer (done) | time=0ms
[DEBUG] [15:35:21.067] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:35:21.068] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:35:21.068] Initializer GerritInitializer
[DEBUG] [15:35:21.068] [GERRIT PLUGIN] File list already filled. Not calling Gerrit.
[INFO] [15:35:21.068] Initializer GerritInitializer (done) | time=0ms
[DEBUG] [15:35:25.831] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:35:25.832] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:35:25.832] Initializer GerritInitializer
[DEBUG] [15:35:25.832] [GERRIT PLUGIN] File list already filled. Not calling Gerrit.
[INFO] [15:35:25.832] Initializer GerritInitializer (done) | time=0ms
[DEBUG] [15:35:32.083] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:35:32.084] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:35:32.084] Initializer GerritInitializer
[DEBUG] [15:35:32.084] [GERRIT PLUGIN] File list already filled. Not calling Gerrit.
[INFO] [15:35:32.084] Initializer GerritInitializer (done) | time=0ms
[DEBUG] [15:35:35.238] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:35:35.238] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:35:35.239] Initializer GerritInitializer
[DEBUG] [15:35:35.239] [GERRIT PLUGIN] File list already filled. Not calling Gerrit.
[INFO] [15:35:35.239] Initializer GerritInitializer (done) | time=0ms
[DEBUG] [15:35:39.340] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:35:39.341] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:35:39.342] Initializer GerritInitializer
[DEBUG] [15:35:39.342] [GERRIT PLUGIN] File list already filled. Not calling Gerrit.
[INFO] [15:35:39.342] Initializer GerritInitializer (done) | time=0ms
[DEBUG] [15:35:39.428] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:35:39.430] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:35:39.430] Initializer GerritInitializer
[DEBUG] [15:35:39.430] [GERRIT PLUGIN] File list already filled. Not calling Gerrit.
[INFO] [15:35:39.430] Initializer GerritInitializer (done) | time=0ms
[DEBUG] [15:35:39.471] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:35:39.471] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:35:39.472] Initializer GerritInitializer
[DEBUG] [15:35:39.472] [GERRIT PLUGIN] File list already filled. Not calling Gerrit.
[INFO] [15:35:39.472] Initializer GerritInitializer (done) | time=0ms
[DEBUG] [15:35:39.504] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:35:39.504] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:35:39.504] Initializer GerritInitializer
[DEBUG] [15:35:39.504] [GERRIT PLUGIN] File list already filled. Not calling Gerrit.
[INFO] [15:35:39.505] Initializer GerritInitializer (done) | time=1ms
[DEBUG] [15:35:39.532] [GERRIT PLUGIN] Instanciating GerritInitializer
[DEBUG] [15:35:39.533] Initializers : GerritInitializer -> FindbugsMavenInitializer
[INFO] [15:35:39.533] Initializer GerritInitializer
[DEBUG] [15:35:39.533] [GERRIT PLUGIN] File list already filled. Not calling Gerrit.
[INFO] [15:35:39.533] Initializer GerritInitializer (done) | time=0ms

**Comment by mildis** [comment]
Hi @tisoft,
Can you specify which version of Gerrit you are using ?

Thanks.

**Comment by tisoft** [comment]
2.10.2

It worked before with that version, only sonar has been updated from 5.0 to 5.1.

I also tried to use the current master version of the plugin and even compiled a version against the 5.1 plugin api, but no success.

**Comment by mildis** [comment]
OK.
I've tried to build against 5.1 but have some troubles.
I'll take a look asap.

**Comment by tisoft** [comment]
This is the changed pom, I used to compile against 5.1: https://github.com/tisoft/sonar-gerrit-plugin/commit/c2ff9ee70c17b4594314a46c9902a488132c222c

**Comment by ILikeCoffee** [comment]
I had to switch from a preview analysis to a normal analysis to get it working with 5.1.

**Comment by mildis** [comment]
OK, got it built.
@ILikeCoffee : did you try incremental mode ?

**Comment by greg7859** [comment]
Warning, the preview and incremental analysis don't commit the result. With the normal analysis, the result will be commited and it will be available in the dashboard.

**Comment by tisoft** [comment]
incremental does not work either for me. I try with normal now, just to verify that it works in that mode

**Comment by mildis** [comment]
Let me know.

**Comment by tisoft** [comment]
Yes, normal mode works. Just preview and incremental are broken in SOnar 5.1

Would it help you, if I send you the debug logs?

**Comment by tisoft** [comment]
maybe related to this: https://github.com/SonarSource/sonarqube/commit/91a01dfc9e3d78cbe8b855912202540a66a74cdf?

**Comment by tisoft** [comment]
Sonar 5.1 disabled executiong PostJobs in preview mode, that is why it is not working anymore. The feature will be reenabled in 5.2 again. I'm currently testing with the 5.2-SNAPSHOT and I can see [DEBUG] [22:07:35.492] [GERRIT PLUGIN] Instanciating GerritPostJob in the log. Unfortunatly I get an exception afterwards. Will try a bit more.

**Comment by mildis** [comment]
You spot it.
Maybe you can post the exception to check if this is a known one.

**Comment by tisoft** [comment]
[INFO] [23:28:46.345] ANALYSIS SUCCESSFUL
[DEBUG] [23:28:46.349] [GERRIT PLUGIN] Instanciating GerritPostJob
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] xxx Parent ....................................... SKIPPED
[INFO] xxx Utils ........................................ SKIPPED
[INFO] xxx Model ........................................ SKIPPED
[INFO] xxx Services API ................................. SKIPPED
[INFO] xxx Services ..................................... SKIPPED
[INFO] xxx UI ........................................... SKIPPED
[INFO] xxx importer ..................................... SKIPPED
[INFO] xxx Application .................................. SKIPPED
[INFO] xxx Client ....................................... SKIPPED
[INFO] xxx Integration Tests ............................ SKIPPED
[INFO] xxx :: RPM packaging ............................. SKIPPED
[INFO] xxx :: RPM Wildfly8x packaging ................... SKIPPED
[INFO] xxx :: RPM Keycloak packaging .................... SKIPPED
[INFO] xxx :: RPM xxx application packaging ........... SKIPPED
[INFO] xxx .............................................. FAILURE [ 37.510 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42.020 s
[INFO] Finished at: 2015-04-17T23:28:46+02:00
[INFO] Final Memory: 66M/496M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.5:sonar (default-cli) on project xxx: org.sonar.core.notification.DefaultNotificationManager has unsatisfied dependency 'class org.sonar.core.properties.PropertiesDao' for constructor 'public org.sonar.core.notification.DefaultNotificationManager(org.sonar.core.notification.db.NotificationQueueDao,org.sonar.core.properties.PropertiesDao)' from org.picocontainer.DefaultPicoContainer@4682882a:212<[Immutable]:org.picocontainer.DefaultPicoContainer@312819ae:19<[Immutable]:org.picocontainer.DefaultPicoContainer@2e68bd3d:44<| -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:sonar-maven-plugin:2.5:sonar (default-cli) on project xxx: org.sonar.core.notification.DefaultNotificationManager has unsatisfied dependency 'class org.sonar.core.properties.PropertiesDao' for constructor 'public org.sonar.core.notification.DefaultNotificationManager(org.sonar.core.notification.db.NotificationQueueDao,org.sonar.core.properties.PropertiesDao)' from org.picocontainer.DefaultPicoContainer@4682882a:212<[Immutable]:org.picocontainer.DefaultPicoContainer@312819ae:19<[Immutable]:org.picocontainer.DefaultPicoContainer@2e68bd3d:44<|
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: org.sonar.core.notification.DefaultNotificationManager has unsatisfied dependency 'class org.sonar.core.properties.PropertiesDao' for constructor 'public org.sonar.core.notification.DefaultNotificationManager(org.sonar.core.notification.db.NotificationQueueDao,org.sonar.core.properties.PropertiesDao)' from org.picocontainer.DefaultPicoContainer@4682882a:212<[Immutable]:org.picocontainer.DefaultPicoContainer@312819ae:19<[Immutable]:org.picocontainer.DefaultPicoContainer@2e68bd3d:44<|
	at org.codehaus.mojo.sonar.bootstrap.ExceptionHandling.handle(ExceptionHandling.java:41)
	at org.codehaus.mojo.sonar.bootstrap.RunnerBootstraper.execute(RunnerBootstraper.java:139)
	at org.codehaus.mojo.sonar.SonarMojo.execute(SonarMojo.java:138)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: org.sonar.core.notification.DefaultNotificationManager has unsatisfied dependency 'class org.sonar.core.properties.PropertiesDao' for constructor 'public org.sonar.core.notification.DefaultNotificationManager(org.sonar.core.notification.db.NotificationQueueDao,org.sonar.core.properties.PropertiesDao)' from org.picocontainer.DefaultPicoContainer@4682882a:212<[Immutable]:org.picocontainer.DefaultPicoContainer@312819ae:19<[Immutable]:org.picocontainer.DefaultPicoContainer@2e68bd3d:44<|
	at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:191)
	at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:110)
	at org.picocontainer.injectors.ConstructorInjector.access$100(ConstructorInjector.java:51)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:331)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:698)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:646)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:620)
	at org.picocontainer.containers.ImmutablePicoContainer.getComponent(ImmutablePicoContainer.java:40)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:717)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:646)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:631)
	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:605)
	at org.picocontainer.DefaultPicoContainer.getComponents(DefaultPicoContainer.java:586)
	at org.sonar.api.platform.ComponentContainer.getComponentsByType(ComponentContainer.java:222)
	at org.sonar.batch.bootstrap.BatchExtensionDictionnary.completeBatchExtensions(BatchExtensionDictionnary.java:137)
	at org.sonar.batch.bootstrap.BatchExtensionDictionnary.getExtensions(BatchExtensionDictionnary.java:131)
	at org.sonar.batch.bootstrap.BatchExtensionDictionnary.getFilteredExtensions(BatchExtensionDictionnary.java:100)
	at org.sonar.batch.bootstrap.BatchExtensionDictionnary.select(BatchExtensionDictionnary.java:77)
	at org.sonar.batch.phases.PostJobsExecutor.execute(PostJobsExecutor.java:49)
	at org.sonar.batch.phases.DatabaseLessPhaseExecutor.execute(DatabaseLessPhaseExecutor.java:103)
	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:232)
	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93)
	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78)
	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:238)
	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:233)
	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:223)
	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93)
	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78)
	at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:57)
	at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:45)
	at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:135)
	at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:93)
	at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:78)
	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:158)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
	at org.sonar.runner.api.Runner.execute(Runner.java:100)
	at org.codehaus.mojo.sonar.bootstrap.RunnerBootstraper.execute(RunnerBootstraper.java:135)
	... 22 more
[DEBUG] [23:28:47.222] Connection manager is shutting down
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[DEBUG] [23:28:47.236] http-outgoing-0: Close connection
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[DEBUG] [23:28:47.238] http-outgoing-0: Close connection
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :xxx
[DEBUG] [23:28:47.238] Connection manager shut down
SonarQube analysis completed: FAILURE
Build step 'SonarQube' changed build result to FAILURE
Build step 'SonarQube' marked build as failure
Xvfb stopping
Finished: FAILURE

**Comment by tisoft** [comment]
Just tried it with normal mode and 5.2-SNAPSHOT. The excetion is not thrown there and the results are pushed back to gerrit as expected.

**Comment by mildis** [comment]
I was able to reproduce the problem.
Not your exception but the non-push even with 5.2-M8.

It looks like the Decorator is not called either.

From your former log trace, I see no log of the JSON retrieved from Gerrit.
Something like :

`)]}
{
"/COMMIT_MSG": {
      "status": "A"
}}`

Do you have it ?

**Comment by tisoft** [comment]
Yes that is there.

```
[INFO] [12:16:06.017] [GERRIT PLUGIN] Entity 1: )]}'
{
  "/COMMIT_MSG": {
    "status": "A",
    "lines_inserted": 10
  },
  "ui/src/main/webapp/function/TableFactoryFunction.js": {
    "lines_inserted": 58,
    "lines_deleted": 2
  }
}
```

**Comment by mildis** [comment]
I'm checking with SQ dev if we do not have the same issue with Decorator than with PostJob.
I'll update asap.

**Comment by tisoft** [comment]
The exception was caused by the issue assign plugin. I disabled that for previews and now its running through. The postjob is executed and sends the +1 to gerrit, unfortunatly the decorators are not executed, so no issues will ever be found. So this confrims your thoughts from your last comment, from my side.

**Comment by tisoft** [comment]
I have done a quick and dirty fix, so that the plugin works again with sonar 5.2. I removed the decorator and put the stuff it does inside the post job:
https://github.com/tisoft/sonar-gerrit-plugin/commit/225c55d1bfc60757d13a93077df58dc47a6da567

With this change I can at least check my changesets again. :)

**Comment by mildis** [comment]
Aww man, this is bad … but at least you can push back to Gerrit.
@henryju : can the Decorator execution be restored in incremental and preview runs ? Or are there other ways for a plugin which need to collect Issue to get them and send them to an external tool without a Decorator ?

**Comment by henryju** [comment]
@mildis Using a PostJob is the good option. As I'm using the same in the github-plugin I guess it will remain stable enough (except in 5.1).

**Comment by tisoft** [comment]
I have rebased my changes to current master and created a pull request. Maybe we can use that as a base to get the 5.2 compatibility in.

**Comment by megglos** [comment]
Postjob execution was backported to 5.1.1 :) 
http://jira.sonarsource.com/browse/SONAR-6398
