### ISSUE TITLE
Problem handling ~/.ssh/known_hosts

### ISSUE THREAD

**Issue by egorse** [tech-advantage/sonar-gerrit-plugin#45]
Seems #43 is not really working (at least for me) - the ~ is not expanded so it can not create file (IOException) and can not detect the file exists. 
```
12:07:44.539 DEBUG: [GERRIT PLUGIN] SSH will not check host key.
12:07:44.539 DEBUG: [GERRIT PLUGIN] ~/.ssh/known_hosts does not exist. Creating.
12:07:44.540 WARN: [GERRIT PLUGIN] Could not create known_hosts
java.nio.file.NoSuchFileException: ~/.ssh/known_hosts
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.createFile(Files.java:632)
	at fr.techad.sonar.gerrit.network.ssh.GerritSshConnector.getSshClient(GerritSshConnector.java:83)
	at fr.techad.sonar.gerrit.network.ssh.GerritSshConnector.listFiles(GerritSshConnector.java:42)
	at fr.techad.sonar.gerrit.network.ssh.GerritSshFacade.fillListFilesFomGerrit(GerritSshFacade.java:29)
	at fr.techad.sonar.gerrit.GerritFacade.listFiles(GerritFacade.java:40)
	at fr.techad.sonar.GerritInitializer.execute(GerritInitializer.java:34)
	at org.sonar.api.batch.Initializer.execute(Initializer.java:52)
	at org.sonar.scanner.phases.InitializersExecutor.execute(InitializersExecutor.java:62)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.executeInitializersPhase(AbstractPhaseExecutor.java:144)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:74)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:281)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
```

SQ 7.0 sonar scanner 3.0.3.778 run under docker.
The file exists and was just perfectly created manually (no permissions problem)

**Comment by egorse** [comment]
This was testes with master from Mar 01 2017

**Comment by mildis** [comment]
Can you try with the latest master #47 ?

**Comment by mildis** [comment]
Solved
