### ISSUE TITLE
2.4.0 snapshot not working with SQ7.0

### ISSUE THREAD

**Issue by egorse** [tech-advantage/sonar-gerrit-plugin#46]
There is some exception at the end. 2.3.0 meanwhile works fine

``````12:07:59.002 INFO: ANALYSIS SUCCESSFUL
12:07:59.013 INFO: ------------------------------------------------------------------------
12:07:59.014 INFO: EXECUTION FAILURE
12:07:59.014 INFO: ------------------------------------------------------------------------
12:07:59.014 INFO: Total time: 24.629s
12:07:59.305 INFO: Final Memory: 67M/2322M12:07:59.305 ERROR: Error during SonarQube Scanner execution
12:07:59.305 INFO: ------------------------------------------------------------------------

org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: fr.techad.sonar.GerritPostJob has unsatisfied dependency 'class fr.techad.sonar.utils.MessageUtils' for constructor 'public fr.techad.sonar.GerritPostJob(org.sonar.api.config.Settings,fr.techad.sonar.GerritConfiguration,fr.techad.sonar.gerrit.factory.GerritFacadeFactory,fr.techad.sonar.gerrit.utils.ReviewUtils,fr.techad.sonar.utils.MessageUtils)' from org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@b82ce8:287<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@1d3ac898:255<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@6e2aa843:7<[Immutable]:org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer@1543b936:44<|
	at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:191)
	at org.picocontainer.injectors.ConstructorInjector.getGreediestSatisfiableConstructor(ConstructorInjector.java:110)
	at org.picocontainer.injectors.ConstructorInjector.access$100(ConstructorInjector.java:51)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:331)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getLocalInstance(DefaultPicoContainer.java:606)
	at org.picocontainer.DefaultPicoContainer.getComponents(DefaultPicoContainer.java:587)
	at org.sonar.core.platform.ComponentContainer.getComponentsByType(ComponentContainer.java:274)
	at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.completeBatchExtensions(ScannerExtensionDictionnary.java:148)
	at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.getExtensions(ScannerExtensionDictionnary.java:143)
	at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.getFilteredExtensions(ScannerExtensionDictionnary.java:124)
	at org.sonar.scanner.bootstrap.ScannerExtensionDictionnary.select(ScannerExtensionDictionnary.java:74)
	at org.sonar.scanner.phases.PostJobsExecutor.execute(PostJobsExecutor.java:52)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:94)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:111)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
12:07:59.310 DEBUG: Execution getVersion
12:07:59.311 DEBUG: Execution stop
```

**Comment by greg7859** [comment]
A pull request is in progress (#48),
