### ISSUE TITLE
Plugin failed to load with latest 7.3

### ISSUE THREAD

**Issue by mildis** [tech-advantage/sonar-gerrit-plugin#55]
SonarSource dropped API deprecated before 5.6
https://docs.sonarqube.org/display/SONAR/Release+7.3+Upgrade+Notes

It results in the following stack trace when starting SQ 7.3 with the plugin :
```2018.08.13 18:00:48 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin Gerrit Reviewer [gerrit]
    at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
    at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:586)
    at org.sonar.server.platform.Platform.start(Platform.java:211)
    at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
    at org.sonar.server.platform.Platform.access$500(Platform.java:46)
    at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
    at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
    at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
    at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/sonar/api/batch/Initializer
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
    at org.sonar.classloader.ClassRealm.loadClassFromSelf(ClassRealm.java:125)
    at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:37)
    at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
    at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
    at fr.techad.sonar.GerritPlugin.define(GerritPlugin.java:111)
    at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
    ... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.api.batch.Initializer
    at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
    at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
    at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
    ... 24 common frames omitted
```

**Comment by mildis** [comment]
Solved
